name: Publish Docker image

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Log in to GHCR using PAT
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ashrafutuyubahe
          password: ${{ secrets.GHCR_PAT }}

      # 3️⃣ Build & push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/ashrafutuyubahe/ecommerce-frontend:latest
